### ISSUE TITLE
Intercepts only full URL

### ISSUE THREAD

**Issue by agilov** [codecept-js/mock-request#3]
I try to mock request to my API "http://localhost:4007/user/auth/login".

I use this code:

```
I.mockRequest('POST', '/user/auth/login', 422, {
        username: ['Invalid']
});
```

And nothing happens - polly js passes thru this request to the actual API.

But when I replace partial url with the full one everything works fine:

```
I.mockRequest('POST', 'http://localhost:4007/user/auth/login', 422, {
        username: ['Invalid']
});
```

In documentation there is a lot of examples with partial urls.

My codecept.conf.js:
```
require('dotenv').config();
const {setHeadlessWhen, setWindowSize} = require('@codeceptjs/configure');
const headless = !!parseInt(process.env.HEADLESS);

setHeadlessWhen(headless);
setWindowSize(1400, 1000);

exports.config = {
    tests: './**/*.e2e.js',
    output: './tests/e2e/output',
    helpers: {
        // Reference: https://codecept.io/helpers/Puppeteer/
        Puppeteer: {
            url: process.env.BASE_URL || 'http://localhost:3000',
            show: !headless, // hides browser in headless mode
            chrome: {
                args: [
                    '--disable-web-security',
                ],
            }
        },
        MockRequestHelper: {
            require: '@codeceptjs/mock-request',
        }
    },
    include: {
        I: './tests/e2e/support/steps_file.js'
    },
    plugins: {
        retryFailedStep: {
            enabled: true,
        },
        screenshotOnFail: {
            enabled: true
        },
        autoLogin: {
            enabled: true,
            // saveToFile: true,
            inject: 'login',
            users:{
                admin: {
                    login: (I) => {
                        I.amOnPage('/auth');
                        I.waitForText('Sign in');
                        I.fillField('#login___username', 'admin1');
                        I.fillField('#login___password', 'test');
                        I.click('Sign in');
                        I.waitForText('Have a nice day', 5);
                    },
                    check: (I) => I.waitForText('Have a nice day, bitch!'),
                    fetch: (I) => {
                        return I.executeScript(() => localStorage.getItem('state'));
                    },
                    restore: (I, session) => {
                        I.amOnPage('/auth');
                        I.executeScript((session) => localStorage.setItem('state', session), session);
                        I.amOnPage('/');
                        I.waitForText('Have a nice day')
                    },
                }
            }
        }
    },
    name: 'vue e2e tests'
};

```

**Comment by code1x1** [comment]
same problem

**Comment by CodyJLeeApps** [comment]
Bump - same here.
Any workaround to this issue? I was hoping we could use regex, but it doesn't look like that works either.

**Comment by CodyJLeeApps** [comment]
@agilov @code1x1 
So an update on this, just in case it will help anyone else.
I have a URL that looks pretty normal, like this: `https://<baseUrl>/details-page/<userId>/details-widget?<parameters>`

I've been trying to get these intercepts to work without having to dynamically build the <userId> and the date that's within a parameter. What I ended up figuring out is that I have to construct the URL in one of these ways, otherwise the intercept does not work.

`https://<baseUrl>/details-page/*/details-widget?*`
`/details-page/*/details-widget?*`

The key here is that I had to make sure I left the '?' in before the wildcard for the parameters. 
Note: I was also trying to use a wildcard inside the base url (for env designations like dev, qa, etc) but that causes a failure as well, but you can completely remove the base url... that's good enough for me. Hopefully this helps someone else!

**Comment by kobenguyent** [comment]
You may try the mock request built in by Puppeteer helper -> https://codecept.io/puppeteer/#mocking-network-requests

**Comment by code1x1** [comment]
Thanks for mentioning me @CodyJLeeApps. We migrated to cypress anyway. Never looking back :partying_face:

**Comment by kobenguyent** [comment]
@code1x1 since many years past. Codeceptjs has envolved a lot. Give it a try, you will be surprised.
